Feat  implementation
17Trafalgar/Server pull request #2
Opened 2022-11-10 05:48 UTC by 17Trafalgar

2022-11-10 05:50 UTC, kmescharikov requested changes

2022-11-10 05:50 UTC, kmescharikov commented on src/out-first-route.js
> +
у тебя в index.js то же самое, убери оттуда, не нужно дублировать код

2022-11-10 05:50 UTC, kmescharikov commented on src/index.js
>    }
зачем тебе файл index.js, если ты всё то же самое делаешь в server.js и приложение у тебя запускается из server.js? удали index.js

2022-11-10 06:20 UTC, kmescharikov commented on src/index.js
>    }
1

2022-11-10 06:33 UTC, 17Trafalgar commented on src/index.js
>    }
Вопрос такой: нужен ли мне этот кусок кода use strick:  (экспорт) в файле server.js, так как такой кусок уже есть в файле our-first-route.js?

2022-11-10 06:33 UTC, 17Trafalgar commented on src/index.js
>    }
И если да, то правильно ли он написан?

2022-11-10 06:33 UTC, 17Trafalgar commented on src/index.js
>    }
111111

2022-11-10 06:35 UTC, 17Trafalgar reviewed
Вопрос такой: нужен ли мне этот кусок кода use strick: (экспорт) в файле server.js, так как такой кусок уже есть в файле our-first-route.js?

2022-11-10 06:35 UTC, 17Trafalgar commented on src/index.js
>    }
Вопрос такой: нужен ли мне этот кусок кода use strick: (экспорт) в файле server.js, так как такой кусок уже есть в файле our-first-route.js?

2022-11-10 06:35 UTC, kmescharikov commented
> Вопрос такой: нужен ли мне этот кусок кода use strick: (экспорт) в файле server.js, так как такой кусок уже есть в файле our-first-route.js?

да, эта директива отдельна для каждого файла

2022-11-10 06:43 UTC, 17Trafalgar commented
> > Вопрос такой: нужен ли мне этот кусок кода use strick: (экспорт) в файле server.js, так как такой кусок уже есть в файле our-first-route.js?
> 
> да, эта директива отдельна для каждого файла

2022-11-10 06:51 UTC, kmescharikov requested changes

2022-11-10 06:51 UTC, kmescharikov commented on src/server.js
> +
не нужно копировать и вставлять бездумно код, эта директива не нуждается в скобках и должна быть в самом начале фейла

2022-11-10 06:51 UTC, kmescharikov commented on src/server.js
> +};
зачем тебе это здесь?
```js
fastify.get(***)
```
это ROUTE, ты подключаешь все свои роуты на 10 строке, это лишнее, убирай

2022-11-11 04:59 UTC, kmescharikov approved these changes

2022-11-13 10:38 UTC, merged